nginx-proxy:
  image: jwilder/nginx-proxy:0.2.0
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
nginx-nikokiuru:
  image: nginx:1.9.6
  volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./www/nikokiuru:/var/www/nikokiuru
  links:
    - fpm
    - mysql
  environment:
    - VIRTUAL_HOST=nikokiuru.com
fpm:
  image: kiuru/php:5.6.15-fpm
  volumes:
    - ./www/nikokiuru:/var/www/nikokiuru
  links:
    - mysql
mysql:
  image: mysql:5.7.9
volumes:
  - ./data/mysql:/var/lib/mysql
