nginx:
  image: nginx:1.9.6
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./www/test:/var/www/test
  links:
    - fpm
fpm:
  image: php:5.6.15-fpm
  volumes:
    - ./www/test:/var/www/test
