nginx-proxy:
  restart: always
  image: jwilder/nginx-proxy:0.2.0
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
nginx-nikokiuru:
  restart: always
  image: nginx:1.9.6
  volumes:
    - ./conf.d:/etc/nginx/conf.d:ro
    - ./www/nikokiuru:/var/www/nikokiuru
    - ./log/nginx/nikokiuru:/var/log/nginx
  links:
    - fpm
    - mysql
  environment:
    - VIRTUAL_HOST=nikokiuru.com
fpm:
  restart: always
  image: kiuru/php:5.6.15-fpm
  volumes:
    - ./www/nikokiuru:/var/www/nikokiuru
    - ./php.ini:/usr/local/etc/php/php.ini:ro
  links:
    - mysql
mysql:
  restart: always
  image: mysql:5.7.9
  volumes:
    - ./data/mysql/nikokiuru:/var/lib/mysql
  extends:
    file: ./secrets/nikokiuru.yml
    service: mysql
